DROP SCHEMA IF EXISTS main;
CREATE DATABASE main; 
USE main;
CREATE TABLE task(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(20) NOT NULL,
    descrip TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
